### PR TITLE
Experimental config system

### PR DESCRIPTION
**Pull request by SquidDev**
- Configs are statically defined using `Property<T>` and `Group`.
 - Each plugin gets a config section under `plugins` -> `<class name>`.
 - `JsonAdapter` converts a given config object to and from a `JsonElement`. Ideally this would preserve commented out fields, invalid fields, etc... when saving but I'm not sure how.
 - `ConfigView` takes an arbitrary config object and displays it in a swing window. Ideally this would be abstracted into the renderer somehow.

### CODE REVIEW

**Review by dmarcuse — CHANGES_REQUESTED** [review]
Looks good so far. Docs on the new config system should be added, and the settings GUI is a bit hard to navigate - I think it would look better as a split pane with a tree of groups on the left and the direct children on the right.

**Comment by SquidDev** [comment]
Latest screenshots

Here's a screenshot with a tree view.

We need to have a discussion about how to best handle saving. Namely,
 - Do we write all values, or just non-default ones. The current system does the latter, but it's up for discussion.
 - Do we remove invalid/non-existent proprties from the JSON? I'd argue we should preserve them were possible, though the current system will not do that. As mentioned in the OP, ideally we could preserve formatting that's not really possible.
 - How/when should we save? The easiest solution would be to attach a change listener to every element and fire it for each change. However saving after every key press would get expensive, so we'd want a better way.

**Comment by Lignum** [comment]
> Do we write all values, or just non-default ones. The current system does the latter, but it's up for discussion.

I doubt the user cares if they're using the GUI.

> Do we remove invalid/non-existent proprties from the JSON? I'd argue we should preserve them were possible, though the current system will not do that. As mentioned in the OP, ideally we could preserve formatting that's not really possible.

I don't think preserving formatting is that important, but keeping invalid properties should be a priority, since users may be switching between CCEmuX versions, which would cause it to delete properties which are perfectly valid in newer versions.

> How/when should we save? The easiest solution would be to attach a change listener to every element and fire it for each change. However saving after every key press would get expensive, so we'd want a better way.

Make a save button in the top right? We should still listen to every element, so the button only activates when a change has been made. That way, the user gets a visual response to having saved, being the button being deactivated. I hate programs where you click "Save" and you don't know if it did anything or not.

**Comment by SquidDev** [comment]
Right, I've got it to preserve invalid properties and the rough layout of the original file. It currently saves the config file when closing the GUI, though @Lignum would rather we explicitly ask for permission.

I'd quite like to add a "reset to default" button for each field, just not sure how to make it look good. Seeing as we're switching to GTX I don't know how much effort to expend.

**Comment by dmarcuse** [comment]
As far as defaults go, I think defaults shouldn't be saved - if we change the default value in a future release, it shouldn't require users to go reset it IMO.

**Comment by dmarcuse** [comment]
Couple small things - there's a crash when there's no config file (should be an easy fix) and also we should integrate the config with `Renderer` now rather than just showing it every time it starts - I think we should have it as an _optional_ extension to `Renderer` - something like `public Optional<Runnable> configWindowRunner(...)` or similar?

```
CCEmuX version: unknown
OS name: Linux
OS version: 4.12.10-2-zen
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 9.0.1
JRE architecture: 64

java.nio.file.NoSuchFileException: /home/dominic/.local/share/ccemux/ccemux.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:415)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.base/java.nio.file.Files.newInputStream(Files.java:154)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2827)
	at net.clgd.ccemux.init.UserConfig.load(UserConfig.java:33)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:219)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:79)
```

**Review by dmarcuse — APPROVED** [review]

**Review by Lignum — APPROVED** [review]
Looks good to me. Is this ready to merge?

**Pull request merged**
